# Generated by Django 4.2.16 on 2024-10-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('account_id', models.CharField(max_length=13, unique=True)),
                ('account_name', models.CharField(max_length=200)),
                ('app_token', models.CharField(max_length=40)),
                ('website', models.URLField(blank=True)),
            ],
        ),
    ]
