# Generated by Django 4.2.16 on 2024-10-11 05:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_alter_account_app_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='app_token',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
