# Generated by Django 4.2.16 on 2024-10-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Destination', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='account_id',
            field=models.CharField(default=0, max_length=20, unique=True),
        ),
    ]
