# Generated by Django 4.2.16 on 2024-10-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Destination', '0002_destination_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='account_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
